import React, { useState, useEffect, useRef } from 'react';
import {
  Alert,
  ScrollView,
  Text,
  TouchableOpacity,
  View,
  StyleSheet,
  Animated,
} from 'react-native';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';
import { Ionicons } from '@expo/vector-icons';

import HeatmapWidget from '../components/HeatmapWidget';
import SeverityBadge from '../components/SeverityBadge';
import { saveHistoryItem } from '../services/storageService';
import { colors } from '../utils/theme';
import { useLanguage } from '../context/LanguageContext';
import { getLocalizedResult } from '../utils/localization';

const tabs = ['Treatment', 'Prevention', 'Learn More'];

const toList = (value) => {
  if (Array.isArray(value)) return value;
  if (typeof value === 'string' && value.trim()) return [value];
  return [];
};

const getConfidence = (value) => {
  const number = Number(value);
  if (Number.isNaN(number)) return 0;
  return number <= 1 ? number * 100 : number;
};

export default function ResultScreen({ route, navigation }) {
  const result = route.params?.result;
  const [activeTab, setActiveTab] = useState('Treatment');
  const [saved, setSaved] = useState(false);
  
  const scaleAnim = useRef(new Animated.Value(1)).current;
  const hasAutoOpened = useRef(false);
  const { t, textStyle, language } = useLanguage();

  useEffect(() => {
    if (!result || hasAutoOpened.current) return;

    // Pulse animation for AI Assistant button
    Animated.loop(
      Animated.sequence([
        Animated.timing(scaleAnim, {
          toValue: 1.04,
          duration: 900,
          useNativeDriver: true,
        }),
        Animated.timing(scaleAnim, {
          toValue: 1,
          duration: 900,
          useNativeDriver: true,
        }),
      ])
    ).start();

    // Auto-open chatbot modal 1.2 seconds after scanning results load
    const timer = setTimeout(() => {
      hasAutoOpened.current = true;
      navigateToChatbot();
    }, 1200);

    return () => clearTimeout(timer);
  }, [result]);

  if (!result) return null;

  const confidence = getConfidence(result.confidence);
  const displayResult = getLocalizedResult(result, language);

  const navigateToChatbot = () => {
    navigation.navigate('Chatbot', {
      cropName: result.crop || 'Unknown Crop',
      diseaseName: result.disease || 'Unknown Disease',
      confidence: confidence,
    });
  };

  const heatmapImage =
    result.gradcamImage ||
    result.gradcam_image ||
    result.gradcam ||
    result.heatmap ||
    result.imageUri;

  const saveToHistory = async () => {
    const historyItem = {
      id: result.id || Date.now().toString(),
      disease: result.disease,
      crop: result.crop || 'Unknown Crop',
      confidence,
      severity: result.severity || 'Medium',
      imageUri: result.imageUri,
      gradcamImage: heatmapImage,
      description: result.description,
      treatment: result.treatment,
      prevention: result.prevention,
      learn_more: result.learn_more || result.learnMore,
      date: result.date || new Date().toISOString(),
    };

    const ok = await saveHistoryItem(historyItem);

    if (ok) {
      setSaved(true);
      Alert.alert(t('savedSuccessfully'), t('savedMessage'));
    } else {
      Alert.alert(t('saveFailed'), t('couldNotSave'));
    }
  };

  const shareResult = async () => {
    try {
      const treatmentText = toList(result.treatment).join('\n- ');
      const preventionText = toList(result.prevention).join('\n- ');

      const content = `
LeafDoc Diagnosis Result

Disease: ${result.disease}
Crop: ${result.crop || 'Unknown'}
Confidence: ${confidence.toFixed(1)}%
Severity: ${result.severity || 'Medium'}

Description:
${result.description || 'No description available.'}

Treatment:
- ${treatmentText}

Prevention:
- ${preventionText}

Generated by LeafDoc Plant Disease Detection App.
`;

      const fileUri = `${FileSystem.cacheDirectory}leafdoc-result.txt`;
      await FileSystem.writeAsStringAsync(fileUri, content);

      const available = await Sharing.isAvailableAsync();
      if (!available) {
        Alert.alert(t('sharingNotAvailable'), content);
        return;
      }

      await Sharing.shareAsync(fileUri, {
        mimeType: 'text/plain',
        dialogTitle: t('shareDialog'),
      });
    } catch (error) {
      Alert.alert(t('shareFailed'), error.message);
    }
  };

  const activeData =
    activeTab === 'Treatment'
      ? displayResult.displayTreatment
      : activeTab === 'Prevention'
      ? displayResult.displayPrevention
      : displayResult.displayLearnMore;

  const getTabLabel = (tab) => {
    if (tab === 'Treatment') return t('treatment');
    if (tab === 'Prevention') return t('prevention');
    return t('learnMore');
  };

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <View style={[styles.headerRow, language === 'ur' && { flexDirection: 'row-reverse' }]}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={[styles.backBtn, language === 'ur' ? { marginLeft: 12, marginRight: 0 } : { marginRight: 12 }]}>
          <Ionicons name={language === 'ur' ? 'arrow-forward' : 'arrow-back'} size={22} color={colors.primary} />
        </TouchableOpacity>

        <View style={{ flex: 1 }}>
          <Text style={[styles.headerTitle, textStyle]}>{t('resultTitle')}</Text>
          <Text style={[styles.headerSubtitle, textStyle]}>{t('resultSubtitle')}</Text>
        </View>
      </View>

      <View style={styles.heatmapCard}>
        <HeatmapWidget originalImage={result.imageUri} heatmapImage={heatmapImage} />
        <View style={[styles.xaiMiniBox, language === 'ur' && { flexDirection: 'row-reverse' }]}>
          <Ionicons name="color-wand" size={18} color={colors.primary} />
          <Text style={[styles.xaiMiniText, textStyle, language === 'ur' ? { marginRight: 8, marginLeft: 0 } : { marginLeft: 8 }]}>
            {t('xaiMini')}
          </Text>
        </View>
      </View>

      <View style={styles.diagnosisCard}>
        <Text style={[styles.label, textStyle]}>{t('diseaseName')}</Text>
        <Text style={[styles.diseaseName, textStyle]}>{displayResult.displayDisease || t('unknownDisease')}</Text>

        <View style={[styles.badgeRow, language === 'ur' && { flexDirection: 'row-reverse' }]}>
          <View style={[styles.confidenceBadge, language === 'ur' && { flexDirection: 'row-reverse' }]}>
            <Ionicons name="analytics" size={18} color={colors.primary} />
            <Text style={[styles.confidenceText, language === 'ur' ? { marginRight: 6, marginLeft: 0 } : { marginLeft: 6 }]}>
              {confidence.toFixed(1)}% {t('confident')}
            </Text>
          </View>

          <SeverityBadge severity={result.severity || 'Medium'} />
        </View>

        {/* Premium Animated Ask AI Assistant Card */}
        <Animated.View style={{ transform: [{ scale: scaleAnim }], marginVertical: 10 }}>
          <TouchableOpacity onPress={navigateToChatbot} style={[styles.aiAssistantBanner, language === 'ur' && { flexDirection: 'row-reverse' }]}>
            <View style={[styles.aiBannerLeft, language === 'ur' && { flexDirection: 'row-reverse' }]}>
              <View style={[styles.aiIconWrapper, language === 'ur' ? { marginLeft: 12, marginRight: 0 } : { marginRight: 12 }]}>
                <Ionicons name="chatbubbles" size={20} color="#FFFFFF" />
              </View>
              <View style={{ flexShrink: 1 }}>
                <Text style={[styles.aiBannerTitle, textStyle]}>🤖 {t('askAi')}</Text>
                <Text style={[styles.aiBannerSubtitle, textStyle]}>{t('askAiSubtitle')}</Text>
              </View>
            </View>
            <Ionicons name={language === 'ur' ? 'chevron-back' : 'chevron-forward'} size={22} color={colors.primary} />
          </TouchableOpacity>
        </Animated.View>

        <View style={styles.xaiBox}>
          <View style={[styles.xaiTitleRow, language === 'ur' && { flexDirection: 'row-reverse' }]}>
            <Ionicons name="eye" size={20} color={colors.primary} />
            <Text style={[styles.xaiTitle, language === 'ur' ? { marginRight: 8, marginLeft: 0 } : { marginLeft: 8 }]}>{t('whyAi')}</Text>
          </View>

          <Text style={[styles.xaiText, textStyle]}>
            {displayResult.displayXaiInsight || t('defaultXai')}
          </Text>
        </View>

        <Text style={[styles.description, textStyle]}>
          {displayResult.displayDescription || t('noDescription')}
        </Text>
      </View>

      <View style={[styles.tabsBox, language === 'ur' && { flexDirection: 'row-reverse' }]}>
        {tabs.map((tab) => (
          <TouchableOpacity
            key={tab}
            onPress={() => setActiveTab(tab)}
            style={[styles.tab, activeTab === tab && styles.activeTab]}
          >
            <Text style={[styles.tabText, activeTab === tab && styles.activeTabText]}>
              {getTabLabel(tab)}
            </Text>
          </TouchableOpacity>
        ))}
      </View>

      <View style={styles.detailsCard}>
        {toList(activeData).length === 0 ? (
          <Text style={[styles.detailText, textStyle]}>{t('noDetails')}</Text>
        ) : (
          toList(activeData).map((item, index) => (
            <View key={index} style={[styles.detailRow, language === 'ur' && { flexDirection: 'row-reverse' }]}>
              <View style={[styles.numberCircle, language === 'ur' ? { marginLeft: 12, marginRight: 0 } : { marginRight: 12 }]}>
                <Text style={styles.numberText}>{index + 1}</Text>
              </View>
              <Text style={[styles.detailText, textStyle]}>{item}</Text>
            </View>
          ))
        )}
      </View>

      <View style={[styles.actionRow, language === 'ur' && { flexDirection: 'row-reverse' }]}>
        <TouchableOpacity
          onPress={saveToHistory}
          style={[styles.saveBtn, saved && styles.savedBtn, language === 'ur' ? { marginLeft: 8, marginRight: 0 } : { marginRight: 8 }]}
        >
          <Ionicons
            name={saved ? 'checkmark-circle' : 'bookmark-outline'}
            size={20}
            color={colors.primary}
          />
          <Text style={styles.saveText}>{saved ? t('saved') : t('saveToHistory')}</Text>
        </TouchableOpacity>

        <TouchableOpacity onPress={shareResult} style={[styles.shareBtn, language === 'ur' ? { marginRight: 8, marginLeft: 0 } : { marginLeft: 8 }]}>
          <Ionicons name="share-social" size={20} color="#fff" />
          <Text style={styles.shareText}>{t('shareResult')}</Text>
        </TouchableOpacity>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F6FBF6',
  },
  content: {
    padding: 18,
    paddingBottom: 60,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 18,
    marginBottom: 18,
  },
  backBtn: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#E8F5E9',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  headerTitle: {
    fontSize: 27,
    fontWeight: '900',
    color: '#102A12',
  },
  headerSubtitle: {
    color: '#6A856A',
    marginTop: 2,
    fontSize: 13,
  },
  heatmapCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 14,
    elevation: 3,
  },
  xaiMiniBox: {
    marginTop: 14,
    backgroundColor: '#EEF8EE',
    borderRadius: 14,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  xaiMiniText: {
    flex: 1,
    marginLeft: 8,
    color: '#4F724F',
    fontSize: 13,
    lineHeight: 18,
  },
  diagnosisCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    marginTop: 18,
    elevation: 3,
  },
  label: {
    color: '#6A856A',
    fontSize: 14,
    fontWeight: '600',
  },
  diseaseName: {
    fontSize: 30,
    fontWeight: '900',
    color: '#102A12',
    marginTop: 8,
    textTransform: 'capitalize',
  },
  badgeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 18,
  },
  confidenceBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E8F5E9',
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 18,
  },
  confidenceText: {
    color: colors.primary,
    fontWeight: '900',
    marginLeft: 6,
    fontSize: 15,
  },
  xaiBox: {
    backgroundColor: '#F1F8E9',
    borderRadius: 20,
    padding: 16,
  },
  xaiTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  xaiTitle: {
    color: colors.primary,
    fontWeight: '900',
    fontSize: 17,
    marginLeft: 8,
  },
  xaiText: {
    marginTop: 10,
    color: '#5A7A5A',
    fontSize: 15,
    lineHeight: 22,
  },
  description: {
    marginTop: 18,
    color: '#5A7A5A',
    fontSize: 16,
    lineHeight: 24,
  },
  tabsBox: {
    flexDirection: 'row',
    marginTop: 18,
    backgroundColor: '#EAF4EA',
    borderRadius: 18,
    padding: 6,
  },
  tab: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: 15,
    alignItems: 'center',
  },
  activeTab: {
    backgroundColor: colors.primary,
    elevation: 2,
  },
  tabText: {
    color: '#102A12',
    fontWeight: '800',
    fontSize: 14,
  },
  activeTabText: {
    color: '#FFFFFF',
  },
  detailsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 18,
    marginTop: 14,
    elevation: 2,
  },
  detailRow: {
    flexDirection: 'row',
    marginBottom: 14,
  },
  numberCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#E8F5E9',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  numberText: {
    color: colors.primary,
    fontWeight: '900',
  },
  detailText: {
    flex: 1,
    color: '#5A7A5A',
    fontSize: 15,
    lineHeight: 22,
  },
  actionRow: {
    flexDirection: 'row',
    marginTop: 22,
  },
  saveBtn: {
    flex: 1,
    backgroundColor: '#E8F5E9',
    borderRadius: 18,
    paddingVertical: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    flexDirection: 'row',
  },
  savedBtn: {
    backgroundColor: '#DFF3DF',
  },
  saveText: {
    color: colors.primary,
    fontWeight: '900',
    marginLeft: 6,
  },
  shareBtn: {
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius: 18,
    paddingVertical: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
    flexDirection: 'row',
  },
  shareText: {
    color: '#FFFFFF',
    fontWeight: '900',
    marginLeft: 6,
  },
  aiAssistantBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#E8F5E9',
    borderColor: '#C8E6C9',
    borderWidth: 1.5,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: '#2E7D32',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  aiBannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  aiIconWrapper: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  aiBannerTitle: {
    color: '#0E2F0E',
    fontWeight: '900',
    fontSize: 15,
  },
  aiBannerSubtitle: {
    color: '#4F724F',
    fontSize: 11,
    marginTop: 2,
    fontWeight: '600',
  },
});